<?php
// This script and data application were generated by AppGini 5.50
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/paddata.php");
	include("$currDir/paddata_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('paddata');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "paddata";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`paddata`.`progid`" => "progid",
		"`paddata`.`company`" => "company",
		"`paddata`.`country`" => "country",
		"`paddata`.`website`" => "website",
		"`paddata`.`contactname`" => "contactname",
		"`paddata`.`email`" => "email",
		"`paddata`.`title`" => "title",
		"`paddata`.`version`" => "version",
		"if(`paddata`.`pdate`,date_format(`paddata`.`pdate`,'%m/%d/%Y'),'')" => "pdate",
		"`paddata`.`cost`" => "cost",
		"`paddata`.`ptype`" => "ptype",
		"`paddata`.`status`" => "status",
		"`paddata`.`install`" => "install",
		"`paddata`.`os`" => "os",
		"`paddata`.`languages`" => "languages",
		"`paddata`.`changeinfo`" => "changeinfo",
		"`paddata`.`category`" => "category",
		"`paddata`.`requirements`" => "requirements",
		"`paddata`.`ksize`" => "ksize",
		"`paddata`.`keywords`" => "keywords",
		"`paddata`.`description`" => "description",
		"`paddata`.`descrlarge`" => "descrlarge",
		"`paddata`.`homepage`" => "homepage",
		"`paddata`.`screenshot`" => "screenshot",
		"`paddata`.`icon`" => "icon",
		"`paddata`.`padfile`" => "padfile",
		"`paddata`.`download`" => "download",
		"`paddata`.`dlcount`" => "dlcount",
		"`paddata`.`dlipaddr`" => "dlipaddr",
		"`paddata`.`aspnumber`" => "aspnumber",
		"`paddata`.`affiliate`" => "affiliate",
		"`paddata`.`affiliateid`" => "affiliateid",
		"`paddata`.`siterating`" => "siterating",
		"`paddata`.`clean`" => "clean",
		"`paddata`.`paderrcount`" => "paderrcount"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`paddata`.`progid`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => '`paddata`.`pdate`',
		10 => '`paddata`.`cost`',
		11 => 11,
		12 => '`paddata`.`status`',
		13 => 13,
		14 => 14,
		15 => 15,
		16 => 16,
		17 => 17,
		18 => 18,
		19 => '`paddata`.`ksize`',
		20 => 20,
		21 => 21,
		22 => 22,
		23 => 23,
		24 => 24,
		25 => 25,
		26 => 26,
		27 => 27,
		28 => '`paddata`.`dlcount`',
		29 => 29,
		30 => 30,
		31 => 31,
		32 => 32,
		33 => '`paddata`.`siterating`',
		34 => '`paddata`.`clean`',
		35 => '`paddata`.`paderrcount`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`paddata`.`progid`" => "progid",
		"`paddata`.`company`" => "company",
		"`paddata`.`country`" => "country",
		"`paddata`.`website`" => "website",
		"`paddata`.`contactname`" => "contactname",
		"`paddata`.`email`" => "email",
		"`paddata`.`title`" => "title",
		"`paddata`.`version`" => "version",
		"if(`paddata`.`pdate`,date_format(`paddata`.`pdate`,'%m/%d/%Y'),'')" => "pdate",
		"`paddata`.`cost`" => "cost",
		"`paddata`.`ptype`" => "ptype",
		"`paddata`.`status`" => "status",
		"`paddata`.`install`" => "install",
		"`paddata`.`os`" => "os",
		"`paddata`.`languages`" => "languages",
		"`paddata`.`changeinfo`" => "changeinfo",
		"`paddata`.`category`" => "category",
		"`paddata`.`requirements`" => "requirements",
		"`paddata`.`ksize`" => "ksize",
		"`paddata`.`keywords`" => "keywords",
		"`paddata`.`description`" => "description",
		"`paddata`.`descrlarge`" => "descrlarge",
		"`paddata`.`homepage`" => "homepage",
		"`paddata`.`screenshot`" => "screenshot",
		"`paddata`.`icon`" => "icon",
		"`paddata`.`padfile`" => "padfile",
		"`paddata`.`download`" => "download",
		"`paddata`.`dlcount`" => "dlcount",
		"`paddata`.`dlipaddr`" => "dlipaddr",
		"`paddata`.`aspnumber`" => "aspnumber",
		"`paddata`.`affiliate`" => "affiliate",
		"`paddata`.`affiliateid`" => "affiliateid",
		"`paddata`.`siterating`" => "siterating",
		"`paddata`.`clean`" => "clean",
		"`paddata`.`paderrcount`" => "paderrcount"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`paddata`.`progid`" => "progid",
		"`paddata`.`company`" => "company",
		"`paddata`.`country`" => "country",
		"`paddata`.`website`" => "website",
		"`paddata`.`contactname`" => "contactname",
		"`paddata`.`email`" => "email",
		"`paddata`.`title`" => "title",
		"`paddata`.`version`" => "version",
		"`paddata`.`pdate`" => "pdate",
		"`paddata`.`cost`" => "cost",
		"`paddata`.`ptype`" => "ptype",
		"`paddata`.`status`" => "status",
		"`paddata`.`install`" => "install",
		"`paddata`.`os`" => "os",
		"`paddata`.`languages`" => "languages",
		"`paddata`.`changeinfo`" => "changeinfo",
		"`paddata`.`category`" => "category",
		"`paddata`.`requirements`" => "requirements",
		"`paddata`.`ksize`" => "ksize",
		"`paddata`.`keywords`" => "keywords",
		"`paddata`.`description`" => "description",
		"`paddata`.`descrlarge`" => "descrlarge",
		"`paddata`.`homepage`" => "homepage",
		"`paddata`.`screenshot`" => "screenshot",
		"`paddata`.`icon`" => "icon",
		"`paddata`.`padfile`" => "padfile",
		"`paddata`.`download`" => "download",
		"`paddata`.`dlcount`" => "dlcount",
		"`paddata`.`dlipaddr`" => "dlipaddr",
		"`paddata`.`aspnumber`" => "aspnumber",
		"`paddata`.`affiliate`" => "affiliate",
		"`paddata`.`affiliateid`" => "affiliateid",
		"`paddata`.`siterating`" => "siterating",
		"`paddata`.`clean`" => "clean",
		"`paddata`.`paderrcount`" => "paderrcount"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`paddata`.`progid`" => "progid",
		"`paddata`.`company`" => "company",
		"`paddata`.`country`" => "country",
		"`paddata`.`website`" => "website",
		"`paddata`.`contactname`" => "contactname",
		"`paddata`.`email`" => "email",
		"`paddata`.`title`" => "title",
		"`paddata`.`version`" => "version",
		"if(`paddata`.`pdate`,date_format(`paddata`.`pdate`,'%m/%d/%Y'),'')" => "pdate",
		"`paddata`.`cost`" => "cost",
		"`paddata`.`ptype`" => "ptype",
		"`paddata`.`status`" => "status",
		"`paddata`.`install`" => "install",
		"`paddata`.`os`" => "os",
		"`paddata`.`languages`" => "languages",
		"`paddata`.`changeinfo`" => "changeinfo",
		"`paddata`.`category`" => "category",
		"`paddata`.`requirements`" => "requirements",
		"`paddata`.`ksize`" => "ksize",
		"`paddata`.`keywords`" => "keywords",
		"`paddata`.`description`" => "description",
		"`paddata`.`descrlarge`" => "descrlarge",
		"`paddata`.`homepage`" => "homepage",
		"`paddata`.`screenshot`" => "screenshot",
		"`paddata`.`icon`" => "icon",
		"`paddata`.`padfile`" => "padfile",
		"`paddata`.`download`" => "download",
		"`paddata`.`dlcount`" => "dlcount",
		"`paddata`.`dlipaddr`" => "dlipaddr",
		"`paddata`.`aspnumber`" => "aspnumber",
		"`paddata`.`affiliate`" => "affiliate",
		"`paddata`.`affiliateid`" => "affiliateid",
		"`paddata`.`siterating`" => "siterating",
		"`paddata`.`clean`" => "clean",
		"`paddata`.`paderrcount`" => "paderrcount"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`paddata` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 25;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "paddata_view.php";
	$x->RedirectAfterInsert = "paddata_view.php";
	$x->TableTitle = "Search PAD Data";
	$x->TableIcon = "resources/table_icons/application_form_magnify.png";
	$x->PrimaryKey = "`paddata`.`progid`";
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("progid", "company", "country", "website", "contactname", "email", "title", "version", "pdate", "cost", "ptype", "status", "install", "os", "languages", "changeinfo", "category", "requirements", "ksize", "keywords", "description", "descrlarge", "homepage", "screenshot", "icon", "padfile", "download", "dlcount", "dlipaddr", "aspnumber", "affiliate", "affiliateid", "siterating", "clean", "paderrcount");
	$x->ColFieldName = array('progid', 'company', 'country', 'website', 'contactname', 'email', 'title', 'version', 'pdate', 'cost', 'ptype', 'status', 'install', 'os', 'languages', 'changeinfo', 'category', 'requirements', 'ksize', 'keywords', 'description', 'descrlarge', 'homepage', 'screenshot', 'icon', 'padfile', 'download', 'dlcount', 'dlipaddr', 'aspnumber', 'affiliate', 'affiliateid', 'siterating', 'clean', 'paderrcount');
	$x->ColNumber  = array(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35);

	$x->Template = 'templates/paddata_templateTV.html';
	$x->SelectedTemplate = 'templates/paddata_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `paddata`.`progid`=membership_userrecords.pkValue and membership_userrecords.tableName='paddata' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `paddata`.`progid`=membership_userrecords.pkValue and membership_userrecords.tableName='paddata' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`paddata`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: paddata_init
	$render=TRUE;
	if(function_exists('paddata_init')){
		$args=array();
		$render=paddata_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: paddata_header
	$headerCode='';
	if(function_exists('paddata_header')){
		$args=array();
		$headerCode=paddata_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: paddata_footer
	$footerCode='';
	if(function_exists('paddata_footer')){
		$args=array();
		$footerCode=paddata_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>