<?php
// This script and data application were generated by AppGini 5.50
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/submitlog.php");
	include("$currDir/submitlog_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('submitlog');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "submitlog";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`submitlog`.`submid`" => "submid",
		"concat('<img src=\"', if(`submitlog`.`cstatus`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "cstatus",
		"DATE_FORMAT(`submitlog`.`logtime`, '%c/%e/%Y %l:%i%p')" => "logtime",
		"`submitlog`.`ipaddr`" => "ipaddr",
		"`submitlog`.`company`" => "company",
		"`submitlog`.`country`" => "country",
		"`submitlog`.`website`" => "website",
		"`submitlog`.`contactname`" => "contactname",
		"`submitlog`.`email`" => "email",
		"`submitlog`.`title`" => "title",
		"`submitlog`.`version`" => "version",
		"if(`submitlog`.`pdate`,date_format(`submitlog`.`pdate`,'%m/%d/%Y'),'')" => "pdate",
		"`submitlog`.`cost`" => "cost",
		"`submitlog`.`ptype`" => "ptype",
		"`submitlog`.`install`" => "install",
		"`submitlog`.`os`" => "os",
		"`submitlog`.`languages`" => "languages",
		"`submitlog`.`changeinfo`" => "changeinfo",
		"`submitlog`.`category`" => "category",
		"`submitlog`.`requirements`" => "requirements",
		"`submitlog`.`ksize`" => "ksize",
		"`submitlog`.`keywords`" => "keywords",
		"`submitlog`.`description`" => "description",
		"`submitlog`.`descrlarge`" => "descrlarge",
		"`submitlog`.`homepage`" => "homepage",
		"`submitlog`.`screenshot`" => "screenshot",
		"`submitlog`.`icon`" => "icon",
		"`submitlog`.`padfile`" => "padfile",
		"`submitlog`.`download`" => "download",
		"`submitlog`.`aspnumber`" => "aspnumber",
		"`submitlog`.`backlink`" => "backlink",
		"`submitlog`.`affiliate`" => "affiliate",
		"`submitlog`.`affiliateid`" => "affiliateid"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`submitlog`.`submid`',
		2 => '`submitlog`.`cstatus`',
		3 => '`submitlog`.`logtime`',
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => '`submitlog`.`pdate`',
		13 => '`submitlog`.`cost`',
		14 => 14,
		15 => 15,
		16 => 16,
		17 => 17,
		18 => 18,
		19 => 19,
		20 => 20,
		21 => '`submitlog`.`ksize`',
		22 => 22,
		23 => 23,
		24 => 24,
		25 => 25,
		26 => 26,
		27 => 27,
		28 => 28,
		29 => 29,
		30 => 30,
		31 => 31,
		32 => '`submitlog`.`affiliate`',
		33 => 33
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`submitlog`.`submid`" => "submid",
		"`submitlog`.`cstatus`" => "cstatus",
		"DATE_FORMAT(`submitlog`.`logtime`, '%c/%e/%Y %l:%i%p')" => "logtime",
		"`submitlog`.`ipaddr`" => "ipaddr",
		"`submitlog`.`company`" => "company",
		"`submitlog`.`country`" => "country",
		"`submitlog`.`website`" => "website",
		"`submitlog`.`contactname`" => "contactname",
		"`submitlog`.`email`" => "email",
		"`submitlog`.`title`" => "title",
		"`submitlog`.`version`" => "version",
		"if(`submitlog`.`pdate`,date_format(`submitlog`.`pdate`,'%m/%d/%Y'),'')" => "pdate",
		"`submitlog`.`cost`" => "cost",
		"`submitlog`.`ptype`" => "ptype",
		"`submitlog`.`install`" => "install",
		"`submitlog`.`os`" => "os",
		"`submitlog`.`languages`" => "languages",
		"`submitlog`.`changeinfo`" => "changeinfo",
		"`submitlog`.`category`" => "category",
		"`submitlog`.`requirements`" => "requirements",
		"`submitlog`.`ksize`" => "ksize",
		"`submitlog`.`keywords`" => "keywords",
		"`submitlog`.`description`" => "description",
		"`submitlog`.`descrlarge`" => "descrlarge",
		"`submitlog`.`homepage`" => "homepage",
		"`submitlog`.`screenshot`" => "screenshot",
		"`submitlog`.`icon`" => "icon",
		"`submitlog`.`padfile`" => "padfile",
		"`submitlog`.`download`" => "download",
		"`submitlog`.`aspnumber`" => "aspnumber",
		"`submitlog`.`backlink`" => "backlink",
		"`submitlog`.`affiliate`" => "affiliate",
		"`submitlog`.`affiliateid`" => "affiliateid"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`submitlog`.`submid`" => "No",
		"`submitlog`.`cstatus`" => "Status",
		"`submitlog`.`logtime`" => "Submission Date",
		"`submitlog`.`ipaddr`" => "IP",
		"`submitlog`.`company`" => "Company Name",
		"`submitlog`.`country`" => "Country",
		"`submitlog`.`website`" => "website",
		"`submitlog`.`contactname`" => "contactname",
		"`submitlog`.`email`" => "email",
		"`submitlog`.`title`" => "Title",
		"`submitlog`.`version`" => "Version",
		"`submitlog`.`pdate`" => "pdate",
		"`submitlog`.`cost`" => "cost",
		"`submitlog`.`ptype`" => "ptype",
		"`submitlog`.`install`" => "install",
		"`submitlog`.`os`" => "os",
		"`submitlog`.`languages`" => "languages",
		"`submitlog`.`changeinfo`" => "changeinfo",
		"`submitlog`.`category`" => "category",
		"`submitlog`.`requirements`" => "requirements",
		"`submitlog`.`ksize`" => "ksize",
		"`submitlog`.`keywords`" => "keywords",
		"`submitlog`.`description`" => "description",
		"`submitlog`.`descrlarge`" => "descrlarge",
		"`submitlog`.`homepage`" => "homepage",
		"`submitlog`.`icon`" => "icon",
		"`submitlog`.`padfile`" => "PAD file",
		"`submitlog`.`download`" => "Download",
		"`submitlog`.`aspnumber`" => "aspnumber",
		"`submitlog`.`backlink`" => "Backlink URL",
		"`submitlog`.`affiliate`" => "Affiliate",
		"`submitlog`.`affiliateid`" => "Affiliate Data"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`submitlog`.`submid`" => "submid",
		"concat('<img src=\"', if(`submitlog`.`cstatus`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "cstatus",
		"DATE_FORMAT(`submitlog`.`logtime`, '%c/%e/%Y %l:%i%p')" => "logtime",
		"`submitlog`.`ipaddr`" => "ipaddr",
		"`submitlog`.`company`" => "company",
		"`submitlog`.`country`" => "country",
		"`submitlog`.`website`" => "website",
		"`submitlog`.`contactname`" => "contactname",
		"`submitlog`.`email`" => "email",
		"`submitlog`.`title`" => "title",
		"`submitlog`.`version`" => "version",
		"if(`submitlog`.`pdate`,date_format(`submitlog`.`pdate`,'%m/%d/%Y'),'')" => "pdate",
		"`submitlog`.`cost`" => "cost",
		"`submitlog`.`ptype`" => "ptype",
		"`submitlog`.`install`" => "install",
		"`submitlog`.`os`" => "os",
		"`submitlog`.`languages`" => "languages",
		"`submitlog`.`changeinfo`" => "changeinfo",
		"`submitlog`.`category`" => "category",
		"`submitlog`.`requirements`" => "requirements",
		"`submitlog`.`ksize`" => "ksize",
		"`submitlog`.`keywords`" => "keywords",
		"`submitlog`.`description`" => "description",
		"`submitlog`.`descrlarge`" => "descrlarge",
		"`submitlog`.`homepage`" => "homepage",
		"`submitlog`.`icon`" => "icon",
		"`submitlog`.`padfile`" => "padfile",
		"`submitlog`.`download`" => "download",
		"`submitlog`.`aspnumber`" => "aspnumber",
		"`submitlog`.`backlink`" => "backlink",
		"`submitlog`.`affiliate`" => "affiliate",
		"`submitlog`.`affiliateid`" => "affiliateid"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`submitlog` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 0;
	$x->RecordsPerPage = 30;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "submitlog_view.php";
	$x->RedirectAfterInsert = "submitlog_view.php";
	$x->TableTitle = "PAD Submissions";
	$x->TableIcon = "resources/table_icons/application_form_magnify.png";
	$x->PrimaryKey = "`submitlog`.`submid`";
	$x->DefaultSortField = '2';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 200, 150, 150, 150, 150, 150);
	$x->ColCaption = array("No", "Submission Date", "IP", "Company Name", "Country", "Title", "Version", "description", "homepage", "Download", "Backlink URL", "Affiliate", "Affiliate Data");
	$x->ColFieldName = array('submid', 'logtime', 'ipaddr', 'company', 'country', 'title', 'version', 'description', 'homepage', 'download', 'backlink', 'affiliate', 'affiliateid');
	$x->ColNumber  = array(1, 3, 4, 5, 6, 10, 11, 23, 25, 29, 31, 32, 33);

	$x->Template = 'templates/submitlog_templateTV.html';
	$x->SelectedTemplate = 'templates/submitlog_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `submitlog`.`submid`=membership_userrecords.pkValue and membership_userrecords.tableName='submitlog' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `submitlog`.`submid`=membership_userrecords.pkValue and membership_userrecords.tableName='submitlog' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`submitlog`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: submitlog_init
	$render=TRUE;
	if(function_exists('submitlog_init')){
		$args=array();
		$render=submitlog_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: submitlog_header
	$headerCode='';
	if(function_exists('submitlog_header')){
		$args=array();
		$headerCode=submitlog_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: submitlog_footer
	$footerCode='';
	if(function_exists('submitlog_footer')){
		$args=array();
		$footerCode=submitlog_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>