<?php
// This script and data application were generated by AppGini 5.50
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/usrreviews.php");
	include("$currDir/usrreviews_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('usrreviews');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "usrreviews";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`usrreviews`.`revid`" => "revid",
		"`usrreviews`.`progid`" => "progid",
		"`usrreviews`.`useripaddr`" => "useripaddr",
		"`usrreviews`.`revtime`" => "revtime",
		"`usrreviews`.`username`" => "username",
		"`usrreviews`.`userrating`" => "userrating",
		"`usrreviews`.`usercomment`" => "usercomment"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`usrreviews`.`revid`',
		2 => '`usrreviews`.`progid`',
		3 => 3,
		4 => '`usrreviews`.`revtime`',
		5 => 5,
		6 => '`usrreviews`.`userrating`',
		7 => 7
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`usrreviews`.`revid`" => "revid",
		"`usrreviews`.`progid`" => "progid",
		"`usrreviews`.`useripaddr`" => "useripaddr",
		"`usrreviews`.`revtime`" => "revtime",
		"`usrreviews`.`username`" => "username",
		"`usrreviews`.`userrating`" => "userrating",
		"`usrreviews`.`usercomment`" => "usercomment"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`usrreviews`.`revid`" => "ID",
		"`usrreviews`.`progid`" => "progid",
		"`usrreviews`.`useripaddr`" => "useripaddr",
		"`usrreviews`.`revtime`" => "revtime",
		"`usrreviews`.`username`" => "username",
		"`usrreviews`.`userrating`" => "userrating",
		"`usrreviews`.`usercomment`" => "usercomment"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`usrreviews`.`revid`" => "revid",
		"`usrreviews`.`progid`" => "progid",
		"`usrreviews`.`useripaddr`" => "useripaddr",
		"`usrreviews`.`revtime`" => "revtime",
		"`usrreviews`.`username`" => "username",
		"`usrreviews`.`userrating`" => "userrating",
		"`usrreviews`.`usercomment`" => "usercomment"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`usrreviews` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 25;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "usrreviews_view.php";
	$x->RedirectAfterInsert = "usrreviews_view.php";
	$x->TableTitle = "User Reviews";
	$x->TableIcon = "resources/table_icons/client_account_template.png";
	$x->PrimaryKey = "`usrreviews`.`revid`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("ID", "progid", "useripaddr", "revtime", "username", "userrating", "usercomment");
	$x->ColFieldName = array('revid', 'progid', 'useripaddr', 'revtime', 'username', 'userrating', 'usercomment');
	$x->ColNumber  = array(1, 2, 3, 4, 5, 6, 7);

	$x->Template = 'templates/usrreviews_templateTV.html';
	$x->SelectedTemplate = 'templates/usrreviews_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `usrreviews`.`revid`=membership_userrecords.pkValue and membership_userrecords.tableName='usrreviews' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `usrreviews`.`revid`=membership_userrecords.pkValue and membership_userrecords.tableName='usrreviews' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`usrreviews`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: usrreviews_init
	$render=TRUE;
	if(function_exists('usrreviews_init')){
		$args=array();
		$render=usrreviews_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: usrreviews_header
	$headerCode='';
	if(function_exists('usrreviews_header')){
		$args=array();
		$headerCode=usrreviews_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: usrreviews_footer
	$footerCode='';
	if(function_exists('usrreviews_footer')){
		$args=array();
		$footerCode=usrreviews_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>